services:
  backend:
    build: ./backend
    ports:
      - "7860:7860"

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
